services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aige-backend
    restart: unless-stopped
    ports:
      - "8182:8182"
    environment:
      # 从.env文件读取环境变量
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_PATH=/app/data/chat.db
      - MODS_PATH=/app/mods
      - ALLOWED_ORIGINS=https://games.yushenjian.com,http://games.yushenjian.com
      - GIN_MODE=${GIN_MODE:-release}
    volumes:
      # 持久化数据库文件
      - ./data:/app/data
      # 挂载MOD目录
      - ./mods:/app/mods:ro
      - ./xiuxian2:/app/xiuxian2:ro
    networks:
      - aige-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8182/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aige-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - aige-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  aige-network:
    driver: bridge

volumes:
  data:
    driver: local
